### ISSUE TITLE
Cannot rotate to portrait mode.

### ISSUE THREAD

**Issue by bryanlarsen** [zielmicha/emacs-android#11]
If I wanted a wide & skinny screen, I'd just use my laptop!   Is there any way of running Emacs in portrait mode?

**Comment by zielmicha** [comment]
If you enable automatic rotation in Android settings, it wil rotate.

**Comment by bryanlarsen** [comment]
Doesn't work for me.   Nexus 7, Android 4.2.  Tried with automatic rotation on, and with rotation locked to portrait.

**Comment by juan-g** [comment]
I can confirm this bug (in my case on an HTC Desire HD 4.3-inch Android smartphone). I have _Menu > Settings > Display > Auto-rotate screen_ enabled, and it works well with many apps to change between landscape and portrait modes, but not for the Emacs app.

For example, I think this Emacs app is based on the [Android Terminal Emulator](http://play.google.com/store/apps/details?id=jackpal.androidterm), which I also have installed. Portrait and landscape both work well with the terminal emulator. However, there is only landscape for the Emacs app, there is no portrait mode. So, probably something went wrong in the customization of the terminal when developing the Emacs app.

The same happens to other people, also with other devices such as Samsung Galaxy S3. From the [Emacs app](http://play.google.com/store/apps/details?id=com.zielm.emacs) user reviews:

> "Need to enable **portrait orientation**!!!
> You need to fix the orientation, and have it not be forced to horizontal. I'm using a Samsunc tablet and want to use it vertical. This is a serious oversight."
> (August 30, 2012 - Version 1.0.1)
> 
> "Excellent App
> An excellent port of the classic. Would be nice to be able to use in **portrait mode** though..."
> (October 18, 2012 - Samsung Galaxy S3 with version 1.0.1)
> 
> "A good start, but still problematic.
> Let me first start by saying the effort to get a TTY-mode emacs running natively under Android, in a dedicated terminal app, is significant, and well worthwhile. That said, the limitations currently keep me from using it. 1. Does not support **portrait mode**, which is a must if you are going to use Hacker's Keyboard rather than a hardware keyboard. [...]"
> (December 4, 2012 - Version 1.0.1)

I think this issue should be reopened. Can anyone find out what file contains the bug that is preventing portrait mode from working?

**Comment by kidd** [comment]
+1 for reopening. it's failing for me also.

Unfortunately, I have no idea of how to start debugging it :(
