### ISSUE TITLE
Emacs segfaults on installation

### ISSUE THREAD

**Issue by vjandrea** [zielmicha/emacs-android#19]
During install, after lisp download, terminal window shows: 
Fatal Error (11)Segmentation fault.
After reboot if i reopen the app to see if the installation may continue, the same error appears.
ICS on HTC G2.

**Comment by mcandre** [comment]
Me, too! Please patch Emacs so that it handles different window and font sizes.

**Comment by vjandrea** [comment]
I'm looking through the code to see where this is handled, but since i don't have a detailed log this is pretty hard. Is there a debug mode for this app?

**Comment by mcandre** [comment]
Anyone know of a source for gdb on Android?

**Comment by aperomsik** [comment]
Does this help? I have used NDK GDB once or twice, but not sure if it will work with the way emacs runs. http://stackoverflow.com/questions/10534367/how-to-get-ndk-gdb-working-on-android

**Comment by zielmicha** [comment]
I used addr2line from Android NDK on adress that is shown in crash dump from adb logcat. Than I inserted debug printf and I found out that a some elisp variable is not initialized (and NULL dereference or abort() follows, I don't remember (abort() is redefined in emacs to something strange). Then I gave up, as the error was in internationalization code, which was to strange for me to handle.

**Comment by mcandre** [comment]
The segfault is somehow related to screen dimensions and font size. If I set the font too big in Android Terminal, or use portrait mode, Emacs crashes. If I use really tiny font in landscape mode, Emacs runs very well.

Something is segfaulting for small screen sizes.

**Comment by zielmicha** [comment]
This is duplicate, main bug is #2 .
