### ISSUE TITLE
Installer assumes /mnt/sdcard exists and is writeable

### ISSUE THREAD

**Issue by alinnow** [zielmicha/emacs-android#20]
The installer tries to write to `/mnt/sdcard` and does not give any opportunity to change the path.

On my Archos G9, the directory exists but is not writeable, so the emacs download fails instantly. I managed to workaround it by `su`ing to root and bind-mounting `/mnt/storage` (the HDD mountpoint) to `/mnt/sdcard`, but I think it would be better if the installer detected this and asked the user to choose another location.

**Comment by mcandre** [comment]
Apps can already write to their respective directories. Why not install Emacs in the Emacs Android app directory?

**Comment by zielmicha** [comment]
Won't fix. Pathes are hardcoded in Emacs config (paths.h or something).
