### ISSUE TITLE
Fatal Error (6)Aborted on KitKat

### ISSUE THREAD

**Issue by shotblocker21** [zielmicha/emacs-android#30]
After downloading the files as it requests when first run, it just gives the error "Fatal error (6)Aborted" when trying to start emacs, then drops to a command prompt in the /data/data/com.zielm.emacs directory.
Running Cyanogenmod 11.

**Comment by Petteri** [comment]
I got this also on my Nexus 10 running android 4.4.2.

**Comment by drnil** [comment]
Same problem here. There is a crash with the above error message on startup, just after loading emacs.bin.lzma. I'm using Nexus 5, Android 4.4.2, Kernel-version 3.4.0-gadb2201 dated 2013-11-20. The phone version is KOT49H.

**Comment by drnil** [comment]
Same problem, identical symptoms on Nexus 7, Android 4.4.2.

**Comment by zielmicha** [comment]
This is probably the same issue as #2. It's left open from two years, because I'm scared of debugging it (or rather too lazy).

**Comment by drnil** [comment]
Thanks a lot for replying! I understand.

Keep up the good work!
I really appreciate your spending your time on this.
