### ISSUE TITLE
busyboxrc.sh no longer available for download

### ISSUE THREAD

**Issue by spchamp** [zielmicha/emacs-android#33]
Hello! I have installed Terminal IDE and Emacs via the Google Play store,  however I have encountered an issue with the downloading of  `/sdcard/emacs/busybox.rc` and I cannot start Emacs via the app launcher.

Reviewing the Readme file, here at Github, it seems that the issue with `busyboxrc.sh` is because http://emacs.zielm.com/data/busyboxrc.sh is no longer available. Correspondingly, I see a HTML file installed at `/sdcard/emacs/busybox.rc`

Might there be an approporiate busyboxrc.sh availble here in the source tree, or perhaps via GitHub Pages?

Personally, I look forward to testing out an Emacs interface to Common Lisp,  [SLIME](http://common-lisp.net/project/slime), on Android . Possibly, [SBCL](http://sbcl.org/) or [CCL](http://ccl.clozure.com/) for ARM might work out as a Common Lisp implementation for this individual study. I might favor CCL, if [CL+J](http://common-lisp.net/project/cl-plus-j/) can be extended for creating a GUI via Java, in CCL - assuming Android is not running an X.org server, by default. 

Perhaps an X.org server app could be useful with this prototype, also - there is a native xlib interface in Common Lisp, [CLX](http://www.cliki.net/CLX).

Of course, those may be applied without Emacs+SLIME as the IDE, but if the latter is available, that would simplify the development of a prototype for this platform -- those, all of free/open source software components portaboe to Linux+ARM.

I'll search for busyboxrc.sh, here and in the [web archive](http://archive.org/web/), towards a workaround for the present item.

**Comment by zielmicha** [comment]
I will restore emacs.zielm.com (hopefully soon).

**Comment by spchamp** [comment]
May there be any advice as to what busyboxrc.sh would contain for shell commands? I am unable to find a mirrored copy of the original file.

I assume that it would launch Emacs, as has been installed on a filesystem on the tablet. I do not know what pathname Emacs was installed to, but I will look further into the source code, here.

Might the shell script have been defined to configure the shell environment, or perform other shell commands other than, I presume, to launch Emacs?

If there is any concern with the domain name and hosting for that feature of the Emacs application., an observation that [GitHub Pages](https://pages.github.com) is available for hosting web sites for GitHub projects

**Comment by zielmicha** [comment]
Fixed.
